import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "../trpc/Provider";
import { getServerSession } from "next-auth";
import SessionProvider from "@/auth/SessionProvider";
import Link from "next/link";
import AuthDropdown from "@/components/app/auth/AuthDropdown";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="relative">
        <SessionProvider session={session}>
          <Provider>
            <nav className=" absolute bg-white top-0 left-0 w-full flex justify-between items-center border-b border-slate-200 shadow-md p-4">
              <div>
                <Link href="/">
                  <Image width={120} height={32} src={"/logo-2.png"} alt="PodFlix" />
                </Link>
              </div>
              <AuthDropdown />
            </nav>
            <div style={{ height: 'calc(100vh - 69px)' }} className="flex flex-col justify-start items-start pt-[69px]">
              {children}
            </div>
          </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
